<a href="https://colab.research.google.com/github/Gayatri230/Bangalore-House-Price-Prediction/blob/main/houseprice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
df = pd.read_csv('/content/data/House Price.csv', usecols=[1,2,3,4,5,6,7,8,9,12,13])

In [ ]:
df.sample(10)

,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,yr_built,yr_renovated
3059,420000.0,3,2.00,1200,5029,1.0,0,0,3,1937,1999
4326,370000.0,4,2.75,3150,67518,1.0,0,0,4,1965,0
4106,148226.0,3,1.00,1400,7360,1.0,0,0,4,1968,0
2832,464000.0,3,1.00,1320,3625,2.0,0,0,3,1900,2005
1694,809000.0,4,1.50,1840,4337,2.0,0,0,4,1917,0
3858,600000.0,5,2.00,2190,9072,1.0,0,0,5,1965,0
568,239950.0,3,1.00,1900,33888,1.5,0,0,4,1942,1982
430,583000.0,4,2.50,2660,4000,2.0,0,0,3,2001,0
202,562000.0,5,2.25,3040,8111,2.0,0,0,3,1984,0
2988,565000.0,4,2.75,3260,4900,2.0,0,0,3,2013,1923


In [ ]:
df.shape

(4598, 11)

In [ ]:
df.isnull().sum()

,0
price,0
bedrooms,0
bathrooms,0
sqft_living,0
sqft_lot,0
floors,0
waterfront,0
view,0
condition,0
yr_built,0


In [ ]:
x = df.iloc[:,1:]
y = df.iloc[:,0]

In [ ]:
x

,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,yr_built,yr_renovated
0,3,1.50,1340,7912,1.5,0,0,3,1955,2005
1,5,2.50,3650,9050,2.0,0,4,5,1921,0
2,3,2.00,1930,11947,1.0,0,0,4,1966,0
3,3,2.25,2000,8030,1.0,0,0,4,1963,0
4,4,2.50,1940,10500,1.0,0,0,4,1976,1992
...,...,...,...,...,...,...,...,...,...,...
4593,3,1.75,1510,6360,1.0,0,0,4,1954,1979
4594,3,2.50,1460,7573,2.0,0,0,3,1983,2009
4595,3,2.50,3010,7014,2.0,0,0,3,2009,0
4596,4,2.00,2090,6630,1.0,0,0,3,1974,0


In [ ]:
y

,price
0,3.130000e+05
1,2.384000e+06
2,3.420000e+05
3,4.200000e+05
4,5.500000e+05
...,...
4593,3.081667e+05
4594,5.343333e+05
4595,4.169042e+05
4596,2.034000e+05


In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x = sc.fit_transform(x)

y = sc.fit_transform(np.array(y).reshape(-1,1))

In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=0)


In [ ]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(x_train, y_train)
y_pred = regressor.predict(x_test)
y_pred


array([[-2.16158951e-01],
       [-2.37508121e-01],
       [-7.31756398e-02],
       [ 4.22980885e-01],
       [-4.64546142e-01],
       [ 9.40288928e-02],
       [-1.36905567e-01],
       [-6.75387329e-01],
       [ 6.59415018e-01],
       [-4.27920381e-01],
       [-2.84161719e-01],
       [-6.14619494e-01],
       [ 7.14903169e-01],
       [ 1.26658396e-01],
       [ 8.13834738e-01],
       [-5.41244826e-01],
       [-1.55392133e-01],
       [ 8.61719296e-01],
       [ 5.20743170e-01],
       [-2.81477737e-01],
       [-7.36557966e-01],
       [ 3.32554648e-01],
       [ 7.58096562e-01],
       [ 1.46996050e+00],
       [-6.03617735e-01],
       [ 1.27628796e-01],
       [ 5.62190080e-01],
       [ 1.83642827e+00],
       [-8.05593838e-01],
       [ 2.08813261e-01],
       [ 1.44973508e+00],
       [-3.33323148e-01],
       [-6.65025334e-01],
       [-5.02776056e-01],
       [-7.23060315e-01],
       [-6.24366188e-01],
       [-3.19622081e-01],
       [-4.37584751e-01],
       [ 4.7

In [ ]:
from sklearn.ensemble import RandomForestRegressor
model = RandomForestRegressor()
model.fit(x_train, y_train)
print(model.score(x_test, y_test))

/usr/local/lib/python3.12/dist-packages/sklearn/base.py:1389: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)


0.4740502960405828


In [ ]:
model.score(x,y)

0.8439919022362685

In [ ]:
x_test

array([[-0.44123687,  1.38958741, -0.52900815, ..., -0.66701597,
         1.21802499, -0.82562297],
       [ 1.75920471, -0.52405196,  0.19773042, ...,  0.80960388,
        -0.09366497, -0.82562297],
       [ 0.65898392,  0.11382783, -0.03067313, ...,  0.80960388,
         0.27629886, -0.82562297],
       ...,
       [-0.44123687, -1.48087164, -1.31803859, ..., -0.66701597,
        -0.0600319 ,  1.23096784],
       [-1.54145766, -1.48087164, -1.39071245, ...,  0.80960388,
        -0.90085879, -0.82562297],
       [ 0.65898392,  0.43276772,  0.10429261, ..., -0.66701597,
         0.41083117,  1.22586211]])

In [ ]:
y_test

array([[-4.28059751e-01],
       [-5.22515587e-01],
       [ 5.77131158e-02],
       [ 5.54280935e-01],
       [-2.52641771e-01],
       [-5.22515587e-01],
       [-3.61940667e-01],
       [-4.88781360e-01],
       [ 1.90634875e+00],
       [-1.04211173e-01],
       [ 6.10954437e-01],
       [-5.56338865e-02],
       [-2.93122844e-01],
       [ 1.11687879e-01],
       [ 8.53840870e-01],
       [-9.27326309e-01],
       [-1.47930731e-01],
       [ 6.89757591e-01],
       [ 3.47827467e-01],
       [ 1.92650023e-01],
       [-5.87015428e-01],
       [ 5.40787245e-01],
       [-1.46707394e+00],
       [ 1.70394339e+00],
       [-8.05883092e-01],
       [ 9.61790396e-01],
       [ 5.83832118e-01],
       [ 1.55551279e+00],
       [-8.59857855e-01],
       [-3.36302654e-01],
       [ 1.86473960e+00],
       [-8.03184354e-01],
       [-2.79629153e-01],
       [ 1.92650023e-01],
       [-7.65402020e-01],
       [-5.25214325e-01],
       [-7.76331910e-01],
       [-5.15768741e-01],
       [ 5.5

In [ ]:
regressor.score(x_test, y_test)

0.539858460064662